
install-requirements:
	pip install -r requirements.txt


download-weights:
	wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1fubTHIa_b2C8HqfbPtKXwoRd9QsYxRL6' -O models/RAFT/raft_sintel.pth
	wget 'https://download.openmmlab.com/mmediting/restorers/basicvsr/spynet_20210409-c6c1bd09.pth' -O models/SPyNet/spynet.pth	


